/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc */

#ifndef _Included_io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc
#define _Included_io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc
#ifdef __cplusplus
extern "C" {
#endif
#undef io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_MODE_SW_ONE_SHOOT
#define io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_MODE_SW_ONE_SHOOT 0L
#undef io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_MODE_SW_CONTINUOUS
#define io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_MODE_SW_CONTINUOUS 1L
#undef io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_MODE_HW_ONE_SHOOT
#define io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_MODE_HW_ONE_SHOOT 2L
#undef io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_MODE_HW_CONTINUOUS
#define io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_MODE_HW_CONTINUOUS 3L
#undef io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_AVG_1
#define io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_AVG_1 0L
#undef io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_AVG_2
#define io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_AVG_2 1L
#undef io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_AVG_4
#define io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_AVG_4 2L
#undef io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_AVG_8
#define io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_AVG_8 3L
#undef io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_AVG_16
#define io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_AVG_16 4L
#undef io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_WORK_MODE_BUSY_POLLING
#define io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_WORK_MODE_BUSY_POLLING 1L
#undef io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_WORK_MODE_TIMER_INT
#define io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_WORK_MODE_TIMER_INT 2L
#undef io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_SYSCLOCK_HZ
#define io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_SYSCLOCK_HZ 1714285.0f
/*
 * Class:     io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc
 * Method:    setup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_setup
  (JNIEnv *, jclass);

/*
 * Class:     io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc
 * Method:    teardown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_teardown
  (JNIEnv *, jclass);

/*
 * Class:     io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc
 * Method:    fetchSamples
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_fetchSamples
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc
 * Method:    configureModule
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_configureModule
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc
 * Method:    configureChannel
 * Signature: (IIIIILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_configureChannel
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc
 * Method:    enableChannel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_enableChannel
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc
 * Method:    disableChannel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_silverspoon_bulldog_beagleboneblack_jni_NativeAdc_disableChannel
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
