/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_silverspoon_bulldog_linux_jni_NativeI2c */

#ifndef _Included_io_silverspoon_bulldog_linux_jni_NativeI2c
#define _Included_io_silverspoon_bulldog_linux_jni_NativeI2c
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeI2c
 * Method:    i2cReadBuffer
 * Signature: ([BII)B
 */
JNIEXPORT jbyte JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeI2c_i2cReadBuffer
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeI2c
 * Method:    i2cRead
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeI2c_i2cRead
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeI2c
 * Method:    i2cWrite
 * Signature: (IB)B
 */
JNIEXPORT jbyte JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeI2c_i2cWrite
  (JNIEnv *, jclass, jint, jbyte);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeI2c
 * Method:    i2cWriteBuffer
 * Signature: ([BII)B
 */
JNIEXPORT jbyte JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeI2c_i2cWriteBuffer
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeI2c
 * Method:    i2cSelectSlave
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeI2c_i2cSelectSlave
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeI2c
 * Method:    i2cOpen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeI2c_i2cOpen
  (JNIEnv *, jclass);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeI2c
 * Method:    i2cClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeI2c_i2cClose
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
