/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_silverspoon_bulldog_linux_jni_NativeMmap */

#ifndef _Included_io_silverspoon_bulldog_linux_jni_NativeMmap
#define _Included_io_silverspoon_bulldog_linux_jni_NativeMmap
#ifdef __cplusplus
extern "C" {
#endif
#undef io_silverspoon_bulldog_linux_jni_NativeMmap_NONE
#define io_silverspoon_bulldog_linux_jni_NativeMmap_NONE 0L
#undef io_silverspoon_bulldog_linux_jni_NativeMmap_READ
#define io_silverspoon_bulldog_linux_jni_NativeMmap_READ 1L
#undef io_silverspoon_bulldog_linux_jni_NativeMmap_WRITE
#define io_silverspoon_bulldog_linux_jni_NativeMmap_WRITE 2L
#undef io_silverspoon_bulldog_linux_jni_NativeMmap_EXEC
#define io_silverspoon_bulldog_linux_jni_NativeMmap_EXEC 4L
#undef io_silverspoon_bulldog_linux_jni_NativeMmap_SHARED
#define io_silverspoon_bulldog_linux_jni_NativeMmap_SHARED 1L
#undef io_silverspoon_bulldog_linux_jni_NativeMmap_PRIVATE
#define io_silverspoon_bulldog_linux_jni_NativeMmap_PRIVATE 2L
/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeMmap
 * Method:    createMap
 * Signature: (JJIIIJ)J
 */
JNIEXPORT jlong JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeMmap_createMap
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jlong);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeMmap
 * Method:    deleteMap
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeMmap_deleteMap
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeMmap
 * Method:    setLongValueAt
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeMmap_setLongValueAt
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeMmap
 * Method:    getLongValueAt
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeMmap_getLongValueAt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeMmap
 * Method:    setIntValueAt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeMmap_setIntValueAt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeMmap
 * Method:    getIntValueAt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeMmap_getIntValueAt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeMmap
 * Method:    setShortValueAt
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeMmap_setShortValueAt
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeMmap
 * Method:    getShortValueAt
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeMmap_getShortValueAt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeMmap
 * Method:    setByteValueAt
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeMmap_setByteValueAt
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeMmap
 * Method:    getByteValueAt
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeMmap_getByteValueAt
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
