/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_silverspoon_bulldog_linux_jni_NativeEpoll */

#ifndef _Included_io_silverspoon_bulldog_linux_jni_NativeEpoll
#define _Included_io_silverspoon_bulldog_linux_jni_NativeEpoll
#ifdef __cplusplus
extern "C" {
#endif
#undef io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLIN
#define io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLIN 1L
#undef io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLPRI
#define io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLPRI 2L
#undef io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLOUT
#define io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLOUT 4L
#undef io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLRDNORM
#define io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLRDNORM 64L
#undef io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLRDBAND
#define io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLRDBAND 128L
#undef io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLWRNORM
#define io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLWRNORM 256L
#undef io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLWRBAND
#define io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLWRBAND 512L
#undef io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLMSG
#define io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLMSG 1024L
#undef io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLERR
#define io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLERR 8L
#undef io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLHUP
#define io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLHUP 16L
#undef io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLRDHUP
#define io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLRDHUP 8192L
#undef io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLWAKEUP
#define io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLWAKEUP 536870912L
#undef io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLONESHOT
#define io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLONESHOT 1073741824L
#undef io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLET
#define io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLLET -2147483648L
#undef io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLL_CTL_ADD
#define io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLL_CTL_ADD 1L
#undef io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLL_CTL_DEL
#define io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLL_CTL_DEL 2L
#undef io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLL_CTL_MOD
#define io_silverspoon_bulldog_linux_jni_NativeEpoll_EPOLL_CTL_MOD 3L
/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeEpoll
 * Method:    epollCreate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeEpoll_epollCreate
  (JNIEnv *, jclass);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeEpoll
 * Method:    addFile
 * Signature: (IILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeEpoll_addFile
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeEpoll
 * Method:    removeFile
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeEpoll_removeFile
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeEpoll
 * Method:    waitForInterrupt
 * Signature: (I)[Lio/silverspoon/bulldog/linux/jni/NativePollResult;
 */
JNIEXPORT jobjectArray JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeEpoll_waitForInterrupt
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeEpoll
 * Method:    stopWait
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeEpoll_stopWait
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeEpoll
 * Method:    shutdown
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeEpoll_shutdown
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
