/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_silverspoon_bulldog_linux_jni_NativeInterrupt */

#ifndef _Included_io_silverspoon_bulldog_linux_jni_NativeInterrupt
#define _Included_io_silverspoon_bulldog_linux_jni_NativeInterrupt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeInterrupt
 * Method:    newEvent
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeInterrupt_newEvent
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
